### ISSUE TITLE
Route API

### ISSUE THREAD

**Issue by finnge** [neuro-inclusive-transit/backend-services#2]
**As** a software developer
**I need** a Service that provides a Route alternatives for set of parameters (start time, start place, end time, end place, preferred transportation-system)
**so that** users can choose their best Route on a set of options.

- [x] neuro-inclusive-transit/development#18
- [x] neuro-inclusive-transit/backend-services#1
- [x] neuro-inclusive-transit/backend-services#23
